const CLICK_SUCCESS = 'CLICK_SUCCESS';
const WAS_VALIDATED_SUCCESS = 'WAS_VALIDATED_SUCCESS';
const ADD_VALIDATE_SUCCESS = 'ADD_VALIDATE_SUCCESS';
const CHANGE_VALIDATE_SUCCESS ='CHANGE_VALIDATE_SUCCESS';
const REMOVE_VALIDATE_SUCCESS = 'REMOVE_VALIDATE_SUCCESS';
const PASSWORD_VALIDATE_SUCCESS = 'PASSWORD_VALIDATE_SUCCESS';
const PASSWORD_STRENGTH_SUCCESS = 'PASSWORD_STRENGTH_SUCCESS';
const EMAIL_VALIDATE_SUCCESS = 'EMAIL_VALIDATE_SUCCESS';
const REMOVE_EMAIL_PASSWORD_VALIDATE_SUCCESS = 'REMOVE_EMAIL_PASSWORD_VALIDATE_SUCCESS';
const ADD_EMAIL_PASSWORD_VALIDATE = 'ADD_EMAIL_PASSWORD_VALIDATE';
const PHONE_VALIDATE_SUCCESS = 'PHONE_VALIDATE_SUCCESS';
const LOGIN_SUCCESS ='LOGIN_SUCCESS';

export {
    LOGIN_SUCCESS,
    CLICK_SUCCESS,
    WAS_VALIDATED_SUCCESS,
    ADD_VALIDATE_SUCCESS,
    CHANGE_VALIDATE_SUCCESS,
    REMOVE_VALIDATE_SUCCESS,
    ADD_EMAIL_PASSWORD_VALIDATE,
    PASSWORD_VALIDATE_SUCCESS,
    PASSWORD_STRENGTH_SUCCESS,
    EMAIL_VALIDATE_SUCCESS,
    PHONE_VALIDATE_SUCCESS,
    REMOVE_EMAIL_PASSWORD_VALIDATE_SUCCESS
}